spring.application.name: department-service
server.port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/department

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/