spring.application.name: employee-service
server.port: 8085

management:
  endpoints:
    web:
      exposure:
        include=*:
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee

cloud:
  loadbalancer:
    retry:
      enabled: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/