spring.application.name: analytics-service
server.port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/analytics

cloud:
  loadbalancer:
    retry:
      enabled: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/